pipeline:
  build:
    image: devforth/drone-builder
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ls -a
      - /bin/bash build.sh
     when:
      branch:
        - master
